// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcQvQpM3f0vSGw0YjteRQlpIDj9IlkmPo',
    appId: '1:981632285882:web:b02ee28cd8af6358a05683',
    messagingSenderId: '981632285882',
    projectId: 'fir-testing-e477c',
    authDomain: 'fir-testing-e477c.firebaseapp.com',
    storageBucket: 'fir-testing-e477c.appspot.com',
    measurementId: 'G-7QKFHT7VD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOUOrlnDk06ip_Z6b6Ig48xFsO5I-qFD4',
    appId: '1:981632285882:android:308e540aa7698315a05683',
    messagingSenderId: '981632285882',
    projectId: 'fir-testing-e477c',
    storageBucket: 'fir-testing-e477c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBht5wBEMgqHfXTCLPEo0VuK7BiBDoqJOw',
    appId: '1:981632285882:ios:530f5a63930f294ea05683',
    messagingSenderId: '981632285882',
    projectId: 'fir-testing-e477c',
    storageBucket: 'fir-testing-e477c.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBht5wBEMgqHfXTCLPEo0VuK7BiBDoqJOw',
    appId: '1:981632285882:ios:530f5a63930f294ea05683',
    messagingSenderId: '981632285882',
    projectId: 'fir-testing-e477c',
    storageBucket: 'fir-testing-e477c.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcQvQpM3f0vSGw0YjteRQlpIDj9IlkmPo',
    appId: '1:981632285882:web:5e5d645a9871338ea05683',
    messagingSenderId: '981632285882',
    projectId: 'fir-testing-e477c',
    authDomain: 'fir-testing-e477c.firebaseapp.com',
    storageBucket: 'fir-testing-e477c.appspot.com',
    measurementId: 'G-1TCMMN4Y8Y',
  );
}
